const jobs = [
  {
    id: 1,
    title: "Senior Frontend Developer",
    company: "Google",
    location: "Bangalore",
    salary: "₹18 LPA",
    type: "Full Time",
    experience: "2-4 Years",
    posted: "2 days ago",
    featured: true,
    skills: ["React", "Node.js", "Remote"],
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "Microsoft",
    location: "Hyderabad",
    salary: "₹22 LPA",
    type: "Full Time",
    experience: "3-5 Years",
    posted: "1 day ago",
    featured: false,
    skills: ["Node.js", "Express", "MySQL"],
  },
  {
    id: 3,
    title: "AI Engineer",
    company: "OpenAI",
    location: "Remote",
    salary: "₹30 LPA",
    type: "Remote",
    experience: "2+ Years",
    posted: "5 hours ago",
    featured: true,
    skills: ["Python", "LLM", "AI"],
  },
];

export default jobs;